tv2/casparcg-cliptool

- src/assets/css/Settings.css
- src/components/App.js
- src/components/Settings.js
- src/index.js
- src/reducers/dataReducer.js
- src/reducers/settingsReducer.js
- src/reducers/templateDataReducer.js
- src/util/CcgLoadPlay.js
- src/util/SettingsStorage.js
- src/util/TimeCodeToString.js
- src/util/filePathStringHandling.js
Settings menu updated to include template overlayFolder
If overlayFolder is set ClipTool looks for a videofile called wipe and will play it during mix
For now, overlay consists of filename inserted in "/HTML-Bundt/BUNDT"
Code cleanup and fixes
> Code CleanUp and preparing overlay graphics

- src/reducers/dataReducer.js
- src/util/HandleOverlay.js
Fixed error when loading before metadata was loaded
> Added emptyMetaList to unloaded datastructure. dataReducer.js

- src/components/App.js
- src/reducers/dataReducer.js
- src/util/HandleAutoNext.js
- src/util/HandleOverlay.js
Workaround: Time range for adding overlay has been raised. 
ToDo:  raise buffer a little more, and make sure the overlay only gets called once.
Autonext:
Added - auto restart if layout has stopped for some reason.
> Overlay - raised timerange for adding overlay. Autonext - autorestart if playout stops

- src/assets/css/App.css
- src/components/App.js
- src/reducers/dataReducer.js
- src/util/CcgLoadPlay.js
- src/util/HandleOverlay.js
- src/util/deepCloneObject.js
Fix: The last version, didn't´t work with more than one output.
Fix: clearing lower thirds when loading new clip before old one has ended
New: Added support for multiple layers in metaData structure.
>  Fix: works with multiple outputs again 

- src/components/App.js
- src/components/Settings.js
- src/components/Thumbnail.js
- src/index.js
- src/reducers/appNavReducer.js
- src/reducers/dataReducer.js
- src/reducers/indexReducer.js
- src/reducers/settingsReducer.js
- src/util/CcgLoadPlay.js
- src/util/HandleAutoNext.js
- src/util/HandleOverlay.js
- src/util/HandleShortcuts.js
- src/util/SettingsStorage.js
Fix: more overlay on more than one output
Refactoring: Redux renaming, and deepClone bugs
Fix: Handling wrong and no metaFiles
> Fix: more overlay on more than one output

- src/components/App.js
- src/components/Thumbnail.js
- src/index.js
- src/reducers/appNavReducer.js
- src/reducers/dataReducer.js
- src/util/CcgLoadPlay.js
- src/util/HandleAutoNext.js
- src/util/HandleOverlay.js
- src/util/HandleShortcuts.js
- src/util/LoadThumbs.js
- src/util/SettingsStorage.js
Added sort list on CCG server, so ClipTool will sort clips when reloading.
(This file also prepare for other services adding a playlist to ClipTool)
A lot of refactoring and Code cleanup
> Drag´n´drop order stored and read on CCG-server.

- .babelrc
- package.json
- src/components/App.js
- src/index.js
- webpack.build.config.js
Fixed: Calling window.__APOLLO_CONNECT__ did not work in production mode.
> Fixed build issues (production mode not working)

- src/util/HandleShortcuts.js
Keys: 1, 2, 3, 4 mix PVW into PGM on corresponding output.
Keys: q, w, e, r start playing clip on output 1, 2, 3 or 4
> Added: Shortcuts works for all outputs and not only the active.

- src/assets/css/App-mini-header.css
- src/assets/css/Rmc-tabs.css
- src/components/App.js
- src/components/Settings.js
- src/components/Thumbnail.js
Further visual work in "Control View"
> Fix: Autonext and Loop buttons did not work after refactoring

- src/assets/css/App-mini-header.css
- src/components/App.js
- src/util/LoadThumbs.js
Autoupdate Thumbnail order when reordering from other machines or externally
UI for control view optimised for Rpi 1280x720
> Autoupdate Thumbnail order when reordering from other machines or externally

- src/assets/css/App-control-view-header.css
- src/assets/css/App-header.css
- src/assets/css/App-mini-header.css
- src/assets/css/App-text-view-header.css
- src/assets/css/Settings.css
- src/assets/css/Thumbnail.css
- src/components/App.js
- src/components/Settings.js
- src/components/Thumbnail.js
- src/reducers/settingsReducer.js
- src/util/CcgLoadPlay.js
- src/util/LoadThumbs.js
UI - Full view, Text view, Control view - Upper left "view" button changes view
Fix: PVW did reset when loading new media in PGM
Settings: Disable drag´n´drop for touchscreen and when an external source controls the order of the clips.
> UI - Full view, Text view, Control view

- src/assets/css/App-text-view-header.css
- src/components/App.js
So it´s easy to reload when other clients has updated settings
> Added Reload button on "mini touch" view.

- package.json
- src/assets/css/Settings.css
- src/components/App.js
- src/components/Settings.js
- src/reducers/settingsReducer.js
- src/util/filePathStringHandling.js
Feat: in settings - media-,data- and template Folders are now selected from pull down menus.
Feat: in settings - "ClipTool Only" disables overlay, wipe and autonext on client. When multiple clients are connected to same server, only one client should handle overlay and autonext.
Style: in settings - better layout of settings.
> mediaFolder, dataFolder and templateFolder pulldown menu

- src/client/components/Header.tsx
- src/client/components/Thumbnail.tsx
- src/client/css/App-header.css
- src/client/css/Thumbnail.css
- src/client/util/TimeCodeToString.ts
- src/gateway/util/TimeCodeToString.ts
- src/model/reducers/settingsAction.ts
- src/model/reducers/settingsReducer.ts
- src/model/videoFormat.ts
Use frame rate specified in the casparcg config per channel.
> Ut 135/use framerate from casparcg config

- src/client/components/Settings.tsx
- src/model/reducers/settingsReducer.ts
- src/server/handlers/CasparCgHandler.ts
Added startup state of loop, mix, manual in settings, for each output.
> feat: Stettings startupstate of Loop, Mix and Manual

- CHANGELOG.md
- package.json
Update of prebuild and release version
> Release v2.14.0

- src/gateway/app.ts
- src/gateway/gateways/AmpServerGateway.ts
- src/gateway/index.ts
- src/gateway/util/SocketGatewayHandlers.ts
- src/gateway/util/extractArgs.ts
- src/server/handlers/CasparCgHandler.ts
- src/server/handlers/expressHandler.ts
- src/server/handlers/socketIOServerHandler.ts
- src/server/utils/SettingsStorage.ts
Updated some log statements to correct syntax along with formatted the message.
Removed unused import statements and unused method.
> fix: Updated incorrect log statements and made logs more consistent.

- src/server/handlers/caspar-cg-handler.ts
- yarn.lock
Adds check for if overlay should be applied, instead of always playing overlay.
> fix: fixes overlays being applied at startup when not suppose to.

- src/client/shared/services/browser-service.ts
- src/shared/reducers/settings-reducer.ts
- src/shared/services/redux-settings-service.ts
I wouldn't say i have testet EVERYTHING after these changes, but i have testet than the indexes that CasparCG is setup for works.
UT-258
> fix: fixes channelview 2 and above not working

- src/server/handlers/amcp-ccg-handler.ts
- src/server/services/casparcg-info-service.ts
Fixes:
- The code was locked to only use layer 10
- If another layer was active without layer 10 was active, Cliptool could crash
> feat: support for defaultLayer from settings instead of code locked to layer 10
